- name: Install nginx repo
  yum_repository:
    name: nginx
    description: nginx repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgkey: http://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
    enabled: yes
    owner: root
    group: root
    mode: 0644
  tags: nginx

- name: Install nginx
  yum:
    name: nginx
    state: present
  tags: nginx

- name: Delete default nginx config
  file:
    dest: "{{ nginx_config_include_path }}/{{ item }}"
    state: absent
  loop:
    - default.conf
    - example_ssl.conf
  tags:
    - nginx
    - nginx_config

- name: Copy main nginx config
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags:
    - nginx
    - nginx_config

- name: Copy nginx rewrite config
  template:
    src: rewrite.conf.j2
    dest: "{{ nginx_config_include_path }}/rewrite.conf"
    owner: root
    group: root
    mode: 0644
  when: nginx_redirect_http
  notify: reload nginx
  tags:
    - nginx
    - nginx_config

- name: Remove nginx rewrite config
  file:
    dest: "{{ nginx_config_include_path }}/rewrite.conf"
    state: absent
  when: not nginx_redirect_http
  notify: reload nginx
  tags:
    - nginx
    - nginx_config

- name: Copy nginx TLS config
  template:
    src: tls.inc.j2
    dest: "{{ nginx_config_include_path }}/tls.inc"
    owner: root
    group: root
    mode: 0644
  when: nginx_tls_enabled
  notify: reload nginx
  tags:
    - nginx
    - nginx_config

- name: Copy TLS public certificate
  copy:
    content: "{{ nginx_tls_crt }}"
    dest: "{{ nginx_tls_cert_path }}/{{ nginx_tls_filename }}.crt"
    owner: root
    mode: 0644
  when:
    - nginx_tls_crt is defined
    - nginx_tls_enabled
  notify: reload nginx
  tags:
    - nginx
    - nginx_config

- name: Copy TLS private key
  copy:
    content: "{{ nginx_tls_key }}"
    dest: "{{ nginx_tls_key_path }}/{{ nginx_tls_filename }}.key"
    owner: root
    group: root
    mode: 0400
  when:
    - nginx_tls_key is defined
    - nginx_tls_enabled
  notify: reload nginx
  tags:
    - nginx
    - nginx_config

- name: Allow nginx to listen on additional ports
  seport:
    context: "{{ item.context_t }}"
    protocol: "{{ item.protocol }}"
    port: "{{ item.port }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ nginx_selinux_ports }}"
  when:
    - ansible_facts.selinux.status == 'enabled'
    - ansible_facts.distribution_version is version_compare('6.6', '>=')
  tags:
    - nginx
    - selinux
    - nginx_config

- name: Allow nginx to proxy open connections
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when:
    - ansible_selinux.status == 'enabled'
    - ansible_distribution_version is version_compare('6.6', '>=')
  tags:
    - nginx
    - selinux
    - nginx_config

- name: Enable and start nginx
  service:
    name: nginx
    state: started
    enabled: true
  tags: nginx
