---
- name: Install nginx repo
  copy:
    src=nginx.repo
    dest=/etc/yum.repos.d/nginx.repo
    owner=root
    group=root
    mode=0644
  tags: nginx

- name: Install nginx
  yum: name=nginx state=present
  tags: nginx

- name: Delete default nginx config
  file: dest=/etc/nginx/conf.d/{{ item }} state=absent
  with_items:
    - default.conf
    - example_ssl.conf
  tags: nginx

- name: Copy main nginx config
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644
  notify: restart nginx
  tags: nginx

- name: Copy nginx rewrite config
  template:
    src=rewrite.conf.j2
    dest=/etc/nginx/conf.d/rewrite.conf
    owner=root
    group=root
    mode=0644
  when: nginx_redirect_http
  notify: reload nginx
  tags: nginx

- name: Copy nginx SSL config
  template:
    src=ssl.inc.j2
    dest=/etc/nginx/conf.d/ssl.inc
    owner=root
    group=root
    mode=0644
  when: nginx_ssl_enabled
  notify: reload nginx
  tags: nginx

- name: Copy SSL public certificate
  copy:
    src=roles/nginx/files/STAR_{{DOMAIN}}.crt
    dest=/etc/pki/tls/certs/
    owner=root
    mode=0644
  when: nginx_ssl_enabled
  notify: reload nginx
  tags: nginx

- name: Copy SSL private key
  template:
    src=server_ssl.inc.j2
    dest=/etc/pki/tls/private/{{ something }}.key
    owner=root
    group=root
    mode=0600
  when: nginx_ssl_enabled
  tags: nginx
  notify: reload nginx

- name: Enable and start nginx
  service:
    name=nginx
    state=started
    enabled=true
  tags: nginx
