---
- name: Install nginx repo
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
  tags: nginx

- name: Install nginx
  yum: name=nginx state=present
  tags: nginx

- name: Delete default nginx config
  file: dest=/etc/nginx/conf.d/{{ item }} state=absent
  with_items:
    - default.conf
    - example_ssl.conf
  tags: nginx

- name: Copy main nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  tags: nginx

- name: Copy nginx rewrite config
  template:
    src: rewrite.conf.j2
    dest: /etc/nginx/conf.d/rewrite.conf
    owner: root
    group: root
    mode: 0644
  when: nginx_redirect_http
  notify: reload nginx
  tags: nginx

- name: Remove nginx rewrite config
  file:
    dest: /etc/nginx/conf.d/rewrite.conf
    state: absent
  when: not nginx_redirect_http
  notify: reload nginx
  tags: nginx

- name: Copy nginx SSL config
  template:
    src: ssl.inc.j2
    dest: /etc/nginx/conf.d/ssl.inc
    owner: root
    group: root
    mode: 0644
  when: nginx_ssl_enabled
  notify: reload nginx
  tags: nginx

- name: Remove nginx SSL config
  file:
    path: /etc/nginx/conf.d/ssl.inc
    state: absent
  when: not nginx_ssl_enabled
  tags: nginx

- name: Copy SSL public certificate
  template:
    src: ssl_crt.j2
    dest: "{{ nginx_ssl_cert_path }}/{{ nginx_ssl_filename }}.crt"
    owner: root
    mode: 0644
  when: nginx_ssl_enabled
  notify: reload nginx
  tags: nginx

- name: Copy SSL private key
  template:
    src: ssl_key.j2
    dest: "{{ nginx_ssl_key_path }}/{{ nginx_ssl_filename }}.key"
    owner: root
    group: root
    mode: 0400
  when: nginx_ssl_enabled
  tags: nginx
  notify: reload nginx

- name: Allow nginx to listen on additional ports
  seport:
    context: "{{ item.context_t }}"
    protocol: "{{ item.protocol }}"
    port: "{{ item.port }}"
    state: "{{ item.state | default('present') }}"
  with_items: nginx_selinux_ports
  when: >
    nginx_selinux_ports is defined and
    ansible_distribution_version | float >=6.6
  tags: [ 'nginx' , 'selinux' , 'esconfig' , 'nginxconfig' , 'kibanaconfig' ]

- name: Allow nginx to proxy open connections
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: >
    nginx_selinux_ports is defined and
    ansible_distribution_version | float >=6.6
  tags: [ 'nginx' , 'selinux' , 'esconfig' , 'nginxconfig' , 'kibanaconfig' ]

- name: Enable and start nginx
  service:
    name: nginx
    state: started
    enabled: true
  tags: nginx
